### ISSUE TITLE
Repos Architecture

### ISSUE THREAD

**Issue by chimo** [cised-ca/se-dir-frontend-react#11]
Eventually, we might want to create a github org. so all repos are together.

Something like:
* cised-ca (org)
  * se-dir-frontend-react (web client: react)
  * se-dir-backend (node/express, mongo)
  * se-dir-wordpress (wordpress variant)
  * se-marketplace-frontend (may or may not be react)
  * se-marketplace-backend (tbd)
  * some-other-future-project-not-related-to-social-enterprises-per-say-maybe-some-internal-cised-tool-or-something-this-is-getting-really-long

We might not need all of those, but you get the idea.

**Comment by nsieber** [comment]
:thumbsup:

**Comment by chimo** [comment]
I think github has redirects going on, but for the record if anyone wants/needs to change their 'remote' URL, this should do it:

Frontend:
`git remote set-url origin https://github.com/cised-ca/se-dir-frontend-react.git`

Backend:
`git remote set-url origin https://github.com/cised-ca/social-enterprise-directory.git`
