### ISSUE TITLE
Todo: Pick a CSS grids framework

### ISSUE THREAD

**Issue by chimo** [cised-ca/se-dir-frontend-react#5]
We currently have rough implementations of:

* [Skeleton](http://getskeleton.com/) ([branch](https://github.com/chimo/cised-web-directory/tree/skeleton.css))
* [Responsive grid system](http://responsivegridsystem.com/) ([branch](https://github.com/chimo/cised-web-directory/tree/responsive-grid-system.css))
* [Bootstrap grids](http://getbootstrap.com/) ([branch](https://github.com/chimo/cised-web-directory/tree/bootstrap-grids.css))
* [Flexbox grids](https://philipwalton.github.io/solved-by-flexbox/demos/grids/) ([branch](https://github.com/chimo/cised-web-directory/tree/flexbox-grids.css))

**Comment by chimo** [comment]
What I like about "responsive grid system":
* Doesn't include anything but grids.

What I like about bootstrap grids:
* Easy to define different number of columns for different viewport sizes (ex: `<div class="col-md-4 col-sm-2">`)
* With a custom, minimal build, we can get just the grids (almost... it still comes with normalize.css, changes the font, etc.)

**Comment by nsieber** [comment]
Responsive grid system also wraps. Just omit the "row" div.

**Comment by nsieber** [comment]
After playing around with 4 columns, 3 columns, and 2 columns, I tend to think that the default single column layout work best on all screen sizes. Otherwise things look kind of cramped. 

To see what I mean switch to branch 'responsive-grid-system.css' and type cycle into the search bar.

**Comment by chimo** [comment]
Ah yeah, I agree.
A grid would look nice if the description was really, really short.

I think what was shown as a possibility at rhok was something similar to [slide 4 in this PDF](https://slack-files.com/files-pri-safe/T1HFYMMDZ-F1LCK6MUJ/slides_cised.pdf?c=1468459874-101b8a96df96973b8f727760f2c838ec4410eaa4).

If that's the way they want to go, we could have a 'tagline' (or wtv) property on the 'enterprise'-type object that would hold a 5-words-max 'tagline'. Or something.

For now we can keep the description and single column setup and see what they say.
What do you think?

**Comment by nsieber** [comment]
Yep sounds good. It's easy enough to change later.
