### ISSUE TITLE
Todo: Backend

### ISSUE THREAD

**Issue by chimo** [cised-ca/se-dir-frontend-react#6]

**Comment by chad-g-adams** [comment]
Did anyone have a particular code organization in mind for the backend? Same repo/different repo?

**Comment by chimo** [comment]
I think a different repo makes sense since, because we're planning around client/server architecture, this repo is just one client of possibly many.

I'm open to alternatives if y'all prefer otherwise though!

**Comment by chad-g-adams** [comment]
Works for me, that's the way I was leaning too

**Comment by chad-g-adams** [comment]
Closing this now, any future issues can be tracked on the backend repo:
https://github.com/cised-ca/social-enterprise-directory
